# Generated by Django 5.1.1 on 2024-10-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_type',
            field=models.CharField(default='EMAIL', max_length=31),
            preserve_default=False,
        ),
    ]
